// // Export SVGs
// export { default as ActivityIcon } from './activity.svg';
// export { default as AfricaFundIcon } from './africaFund.svg';
// export { default as ArcL } from './arc-L.svg';
// export { default as Arc } from './arc.svg';
// export { default as BeaupreneurIcon } from './beaupreneur.svg';
// export { default as CameraMan } from './camera-man.svg';
// export { default as Christina } from './christina.svg';
// export { default as Edwin } from './edwin.svg';
// export { default as ExecProLogo } from './exec-pro-logo.svg';
// export { default as ExecProIcon } from './exec-pro.svg';
// export { default as ExecutiveProCeo } from './executive-pro-ceo.svg';
// export { default as Facebook } from './facebook.svg';
// export { default as ForcytheLogo } from './forcythe-logo.svg';
// export { default as HeaderBackground } from './header-background.svg';
// export { default as Image1 } from './image-1.webp';
// export { default as Image2 } from './image-2.webp';
// export { default as Image } from './image.webp';
// export { default as Instagram } from './instagram.svg';
// export { default as Linkedin } from './linkedin.svg';
// export { default as IwariaFounder } from './iwaria-founder.svg';
// export { default as IwariaIcon } from './iwaria.svg';
// export { default as John } from './john.svg';
// export { default as LayersThreeIcon } from './layers-three.svg';
// export { default as MenuIcon } from './menu.svg';
// export { default as PhoneIcon } from './phone.svg';
// export { default as PlanDesign } from './plan-design.svg';
// export { default as PlanDevelop } from './plan-develop.svg';
// export { default as PlanLaunch } from './plan-launch.svg';
// export { default as PodcastIcon } from './podcast.svg';
// export {default as SS} from './ss.svg';
// export { default as StacIcon } from './stac.svg';
// export { default as StarksIcon } from './starks.svg';
// export { default as StacAI } from './stacai.svg';
// export { default as X} from './x.svg';
// export { default as Youtube } from './youtube.svg';
